version: '3.9'

services:
  app:
    image: testapp
    environment:
      MONGO_URL: 'mongodb://db:27017/test'
    depends_on:
      - db
    ports:
      - '3000-3001:3000'
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
  db:
    image: mongo
